#!/bin/bash -e

evalute(){
  echo $1
  shift

  time "$@"
}

case1(){
  deplug ${options[@]} clean
  deplug ${options[@]} 'mijime/dotfiles' --post 'source .bashrc.d/*.sh' --of '.bashrc.d/*.sh' --use '.bin/*'
  deplug ${options[@]} 'mijime/dat2bar'  --post 'go build' --tag 'master' --use 'dat2bar*'
  deplug ${options[@]} install
}

options=()
options=(--verbose --debug)
options=(--verbose)

source ${0%/*}/source
evalute 'case1' case1
